export const products = [
  {
    id: "123",
    name: "Apple Watch",
    price: 1000,
    description: "This is a Apple watch",
    category: "Watch",
    brand: "Apple",
    inStock: true,
    isOnSale: true,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 3,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "kingkong@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "124",
    name: "Rolex Watch",
    price: 1000,
    description: "This is a Rolex watch",
    category: "Watch",
    brand: "Rolex",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/white.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [],
  },
  {
    id: "125",
    name: "Omega Watch",
    price: 1000,
    description: "This is a Omega watch",
    category: "Watch",
    brand: "Omega",
    inStock: true,
    isOnSale: true,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [],
  },
  {
    id: "126",
    name: "Casio Watch",
    price: 1000,
    description: "This is a Casio watch",
    category: "Watch",
    brand: "Casio",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/white.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 4,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "kingkong@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
      {
        id: "2",
        userId: "2",
        productId: "1",
        rating: 4,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "2",
          name: "queen kong",
          email: "queenkong@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "User",
        },
      },
    ],
  },
  {
    id: "127",
    name: "Patek Philippe Watch",
    price: 1000,
    description: "This is a Patek Philippe watch",
    category: "Watch",
    brand: "Patek Philippe",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@king.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "128",
    name: "Seiko Watch",
    price: 1000,
    description: "This is a Seiko watch",
    category: "Watch",
    brand: "Seiko",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/white.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
  {
    id: "129",
    name: "Hublot Watch",
    price: 1000,
    description: "This is a Hublot watch",
    category: "Watch",
    brand: "Hublot",
    inStock: true,
    isOnSale: false,
    images: [
      {
        color: "gray",
        colorCode: "#d1d5db",
        image: "/images/apple.jpg",
      },
      {
        color: "black",
        colorCode: "#111827",
        image: "/images/apple.jpg",
      },
      {
        color: "white",
        colorCode: "#ffffff",
        image: "/images/apple.jpg",
      },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        productId: "1",
        rating: 5,
        comment: "best watch eveeer!!",
        createdDate: "2023-07-06T06:08:33.067Z",
        user: {
          id: "1",
          name: "king kong",
          email: "king@gmail.com",
          emailVerified: null,
          image: null,
          hashedPassword: null,
          createdAt: "2023-07-06T06:08:33.067Z",
          updatedAt: "2023-07-06T06:08:33.067Z",
          role: "Admin",
        },
      },
    ],
  },
];
