export const product = {
  id: "123",
  name: "Apple Watch",
  price: 1000,
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris convallis imperdiet scelerisque. Etiam suscipit est nec massa consectetur feugiat. Proin sollicitudin cursus diam vitae tincidunt. Vivamus molestie feugiat enim. Sed suscipit eget ligula vel vehicula. Nullam interdum felis vitae nisi tristique viverra. Aenean tristique augue vitae fermentum euismod. Suspendisse pulvi",
  category: "Watch",
  brand: "Apple",
  inStock: true,
  isOnSale: true,
  images: [
    {
      color: "gray",
      colorCode: "#d1d5db",
      image: "/images/apple.jpg",
    },
    {
      color: "black",
      colorCode: "#111827",
      image: "/images/white.jpg",
    },
    {
      color: "white",
      colorCode: "#ffffff",
      image: "/images/white.jpg",
    },
  ],
  reviews: [
    {
      id: "1",
      userId: "1",
      productId: "1",
      rating: 2,
      comment: "worst watch eveeer!!",
      createdDate: "2023-11-22T19:14:33.067Z",
      user: {
        id: "1",
        name: "king kong",
        email: "kingkong@gmail.com",
        emailVerified: null,
        image: null,
        hashedPassword: null,
        createdDate: "2023-11-22T19:14:33.067Z",
        updatedDate: "2023-11-22T19:14:33.067Z",
        role: "Admin",
      },
    },
    {
      id: "2",
      userId: "2",
      productId: "1",
      rating: 5,
      comment: "best watch eveeer!!",
      createdDate: "2023-11-22T19:14:33.067Z",
      user: {
        id: "2",
        name: "king kong",
        email: "asdsad@asdd.dk",
        emailVerified: null,
        image: null,
        hashedPassword: null,
        createdDate: "2023-11-22T19:14:33.067Z",
        updatedDate: "2023-11-22T19:14:33.067Z",
        role: "Admin",
      },
    },
  ],
};
